### ISSUE TITLE
xenial version for the authenticator

### ISSUE THREAD

**Issue by bastos77** [dobey/authenticator-ng#7]
Thank you anyway for your great app! I am using the authenticator since some month as a reliable application for my ubuntu touch based Fairphone 2 daily driver.
UBports is going to release an ubuntu 16.04 LTS (xenial) release in the next days. It would be great to have a authenticator version compiled for the xenial release.

**Comment by dobey** [comment]
The version compiled on 15.04 seems to work just fine on the 16.04 images. If you upgrade with it installed, it should keep working just fine.

**Comment by stekalb** [comment]
Issue is that not everybody has an existing installation on 15.04. For 16.04 authenticator is not visible in openstore.

**Comment by dobey** [comment]
A new version is now in Open Store for 16.04.
